minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.1914fa8195a09e79305a81656dafb5bdd094df75
  vitest: 4.1.9
  vite-plus: 0.0.0-commit.1914fa8195a09e79305a81656dafb5bdd094df75
  '@vitest/coverage-v8': 4.1.9
